export type VehicleType = "stock" | "mandat" | "budget";
export type LabelLevel = "essentiel" | "garanti" | "premium" | "sport";
export type EnergyType = "essence" | "diesel" | "hybride" | "electrique";
export type GearboxType = "manuelle" | "automatique";
export type BodyType = "berline" | "suv" | "utilitaire" | "van" | "moto" | "citadine" | "compacte" | "break";

export interface Vehicle {
  id: string;
  slug: string;
  brand: string;
  model: string;
  version: string;
  year: number;
  price: number;
  monthlyPayment: number;
  mileage: number;
  energy: EnergyType;
  gearbox: GearboxType;
  body: BodyType;
  power: number; // cv
  critair: number;
  location: string;
  type: VehicleType;
  label: LabelLevel;
  image: string;
  images: string[];
  description: string;
  highlights: string[];
  inspectionScore: number; // /100
  warrantyMonths: number;
  available: boolean;
}

export const vehicles: Vehicle[] = [
  {
    id: "v001",
    slug: "range-rover-sport-hse-2021",
    brand: "Land Rover",
    model: "Range Rover Sport",
    version: "3.0 SDV6 HSE Dynamic",
    year: 2021,
    price: 62900,
    monthlyPayment: 689,
    mileage: 47200,
    energy: "diesel",
    gearbox: "automatique",
    body: "suv",
    power: 306,
    critair: 2,
    location: "Showroom Juste à Rouler",
    type: "stock",
    label: "premium",
    image: "/images/vehicules/range-rover-sport/faceee.png",
    images: [
      "/images/vehicules/range-rover-sport/faceee.png",
      "/images/vehicules/range-rover-sport/6d9edd78-7bde-4dd2-aae6-1829e36d1296.png",
      "/images/vehicules/range-rover-sport/ccbcd903-e60a-4a47-8832-b4440e2962b0.png",
      "/images/vehicules/range-rover-sport/f332ccb6-0fcb-4925-a0c2-0ce67cf66ba9.png",
    ],
    description: "Range Rover Sport HSE Dynamic en excellent état. Véhicule Premium labellisé, historique complet, entretien à jour. Intérieur cuir, toit panoramique, système Meridian.",
    highlights: ["Toit panoramique", "Cuir intégral", "Caméra 360°", "Historique complet"],
    inspectionScore: 94,
    warrantyMonths: 12,
    available: true,
  },
  {
    id: "v002",
    slug: "audi-q5-sline-2022",
    brand: "Audi",
    model: "Q5",
    version: "40 TDI 204 S-Line Quattro S-Tronic",
    year: 2022,
    price: 44900,
    monthlyPayment: 489,
    mileage: 34500,
    energy: "diesel",
    gearbox: "automatique",
    body: "suv",
    power: 204,
    critair: 2,
    location: "Showroom Juste à Rouler",
    type: "stock",
    label: "garanti",
    image: "/images/vehicules/audi-q5/face894.png",
    images: [
      "/images/vehicules/audi-q5/face894.png",
      "/images/vehicules/audi-q5/ca1cf052-7355-45b3-93d5-1b570a6cf42a.png",
    ],
    description: "Audi Q5 S-Line Quattro, finition haut de gamme. Transmission intégrale, boîte S-Tronic 7 rapports. Véhicule labellisé Garanti 12 mois.",
    highlights: ["Quattro intégral", "Virtual cockpit", "Matrix LED", "Garantie 12 mois"],
    inspectionScore: 91,
    warrantyMonths: 12,
    available: true,
  },
  {
    id: "v003",
    slug: "peugeot-3008-gt-2023-bleu",
    brand: "Peugeot",
    model: "3008",
    version: "1.5 BlueHDi 130 GT EAT8",
    year: 2023,
    price: 32900,
    monthlyPayment: 359,
    mileage: 18700,
    energy: "diesel",
    gearbox: "automatique",
    body: "suv",
    power: 130,
    critair: 2,
    location: "Showroom Juste à Rouler",
    type: "stock",
    label: "garanti",
    image: "/images/vehicules/peugeot-3008-bleu/face1.png",
    images: [
      "/images/vehicules/peugeot-3008-bleu/face1.png",
      "/images/vehicules/peugeot-3008-bleu/06eb0101-022a-45e4-a3a8-ad98909dd75d.png",
      "/images/vehicules/peugeot-3008-bleu/490dc7a5-e0ff-4281-9a8a-0dd2c6f55d4d.png",
      "/images/vehicules/peugeot-3008-bleu/82a9e999-3872-430c-b7d0-d9bbfd1ff84e.png",
      "/images/vehicules/peugeot-3008-bleu/e59ad029-f8d8-4d6f-9253-4eedbacd99ff.png",
    ],
    description: "Peugeot 3008 GT de 2023, faible kilométrage. i-Cockpit, toit panoramique, aide à la conduite complète. Labellisé Garanti.",
    highlights: ["Faible kilométrage", "i-Cockpit 3D", "Toit panoramique", "Full LED"],
    inspectionScore: 96,
    warrantyMonths: 12,
    available: true,
  },
  {
    id: "v004",
    slug: "peugeot-3008-allure-2020-rouge",
    brand: "Peugeot",
    model: "3008",
    version: "1.5 BlueHDi 130 Allure Business",
    year: 2020,
    price: 21900,
    monthlyPayment: 239,
    mileage: 78400,
    energy: "diesel",
    gearbox: "manuelle",
    body: "suv",
    power: 130,
    critair: 2,
    location: "Showroom Juste à Rouler",
    type: "mandat",
    label: "garanti",
    image: "/images/vehicules/peugeot-3008-rouge/Face2.png",
    images: [
      "/images/vehicules/peugeot-3008-rouge/Face2.png",
      "/images/vehicules/peugeot-3008-rouge/1b3dd3e9-76d7-4fb5-88b1-82c44d2941d9.png",
      "/images/vehicules/peugeot-3008-rouge/9921e15a-ec16-4b38-9342-96d2c8b3d455.png",
      "/images/vehicules/peugeot-3008-rouge/d54141ad-14c0-47be-a558-b56ca085321e.png",
    ],
    description: "Peugeot 3008 Allure Business très bien entretenu. Suivi concession complet. GPS, caméra de recul, régulateur adaptatif.",
    highlights: ["Suivi concession", "GPS intégré", "Caméra de recul", "Apple CarPlay"],
    inspectionScore: 87,
    warrantyMonths: 6,
    available: true,
  },
  {
    id: "v005",
    slug: "audi-a3-sportback-2022",
    brand: "Audi",
    model: "A3 Sportback",
    version: "35 TFSI 150 S-Tronic Design Luxe",
    year: 2022,
    price: 31500,
    monthlyPayment: 345,
    mileage: 29800,
    energy: "essence",
    gearbox: "automatique",
    body: "compacte",
    power: 150,
    critair: 1,
    location: "Showroom Juste à Rouler",
    type: "stock",
    label: "garanti",
    image: "/images/vehicules/audi-a3/face4.png",
    images: [
      "/images/vehicules/audi-a3/face4.png",
      "/images/vehicules/audi-a3/4b283022-1937-4c1c-a3e6-96e021f21f15.png",
      "/images/vehicules/audi-a3/85bfbf1c-d024-4cf2-9d44-772588af24ad.png",
      "/images/vehicules/audi-a3/8db3f5b2-07cf-41ee-9b58-64e123855cb2.png",
      "/images/vehicules/audi-a3/a1a56a98-3e9d-4729-8390-715904a1ea74.png",
      "/images/vehicules/audi-a3/cb108a24-612a-42a4-9172-f9f7abef447c.png",
      "/images/vehicules/audi-a3/ff08fed1-b467-437d-a683-b03621c0d83f.png",
    ],
    description: "Audi A3 Sportback Design Luxe, finition haut de gamme. Cockpit digital, sièges chauffants, éclairage d'ambiance. État remarquable.",
    highlights: ["Cockpit digital", "Sièges chauffants", "Bang & Olufsen", "Carnet complet"],
    inspectionScore: 93,
    warrantyMonths: 12,
    available: true,
  },
  {
    id: "v006",
    slug: "audi-a1-sportback-2021",
    brand: "Audi",
    model: "A1 Sportback",
    version: "30 TFSI 116 S-Line",
    year: 2021,
    price: 22900,
    monthlyPayment: 249,
    mileage: 41200,
    energy: "essence",
    gearbox: "manuelle",
    body: "citadine",
    power: 116,
    critair: 1,
    location: "Showroom Juste à Rouler",
    type: "mandat",
    label: "garanti",
    image: "/images/vehicules/audi-a1/face3.png",
    images: [
      "/images/vehicules/audi-a1/face3.png",
      "/images/vehicules/audi-a1/3351fa3c-acf2-46a4-b650-a0496101fc19.png",
      "/images/vehicules/audi-a1/6d5d15c4-91ca-4578-a9d4-696a6cd6d032.png",
      "/images/vehicules/audi-a1/a722980c-062a-423c-b1eb-bc0c3d5dd200.png",
    ],
    description: "Audi A1 S-Line compacte et dynamique. Idéale en ville, finition soignée. GPS, régulateur, jantes 17 pouces.",
    highlights: ["Pack S-Line", "GPS MMI", "Jantes 17\"", "Radar de recul"],
    inspectionScore: 89,
    warrantyMonths: 6,
    available: true,
  },
  {
    id: "v007",
    slug: "audi-q3-sportback-2023",
    brand: "Audi",
    model: "Q3 Sportback",
    version: "35 TDI 150 S-Tronic S-Line",
    year: 2023,
    price: 41500,
    monthlyPayment: 449,
    mileage: 15600,
    energy: "diesel",
    gearbox: "automatique",
    body: "suv",
    power: 150,
    critair: 2,
    location: "Showroom Juste à Rouler",
    type: "stock",
    label: "premium",
    image: "/images/vehicules/audi-q3/face5.png",
    images: [
      "/images/vehicules/audi-q3/face5.png",
    ],
    description: "Audi Q3 Sportback S-Line quasi neuf. Silhouette coupée, intérieur premium, technologies de pointe. Labellisé Premium.",
    highlights: ["Quasi neuf", "Virtual cockpit+", "Matrix LED", "Caméra 360°"],
    inspectionScore: 97,
    warrantyMonths: 12,
    available: true,
  },
  {
    id: "v008",
    slug: "citroen-c3-feel-2022",
    brand: "Citroën",
    model: "C3",
    version: "1.2 PureTech 83 Feel Pack",
    year: 2022,
    price: 13900,
    monthlyPayment: 149,
    mileage: 32100,
    energy: "essence",
    gearbox: "manuelle",
    body: "citadine",
    power: 83,
    critair: 1,
    location: "Showroom Juste à Rouler",
    type: "budget",
    label: "essentiel",
    image: "/images/vehicules/citroen-c3/face555.png",
    images: [
      "/images/vehicules/citroen-c3/face555.png",
      "/images/vehicules/citroen-c3/2ef74b85-8295-4969-a18d-f245dbfd89b9.png",
      "/images/vehicules/citroen-c3/32993eb7-7b0c-47b4-b434-1b140210f057.png",
      "/images/vehicules/citroen-c3/ef4402ea-e0af-4746-8360-e3a056488876.png",
      "/images/vehicules/citroen-c3/SHOWROOM_MAITRE.png",
    ],
    description: "Citroën C3 Feel Pack, parfaite citadine. Confortable, économique, fiable. Idéale pour un premier véhicule ou un usage quotidien malin.",
    highlights: ["Économique", "Apple CarPlay", "Radar de recul", "Faible consommation"],
    inspectionScore: 84,
    warrantyMonths: 3,
    available: true,
  },
  {
    id: "v009",
    slug: "renault-megane-intens-2021",
    brand: "Renault",
    model: "Mégane",
    version: "1.3 TCe 140 Intens EDC",
    year: 2021,
    price: 18500,
    monthlyPayment: 199,
    mileage: 54300,
    energy: "essence",
    gearbox: "automatique",
    body: "compacte",
    power: 140,
    critair: 1,
    location: "Showroom Juste à Rouler",
    type: "mandat",
    label: "garanti",
    image: "/images/vehicules/renault-megane/face654.png",
    images: [
      "/images/vehicules/renault-megane/face654.png",
      "/images/vehicules/renault-megane/15a711ae-7df4-4481-a6a9-177655bff935.png",
      "/images/vehicules/renault-megane/84f1acc0-301e-4a67-b937-e2d976ab02e9.png",
      "/images/vehicules/renault-megane/9d103eb7-bff8-40f7-ad1f-8e3fcf1f59e1.png",
    ],
    description: "Renault Mégane Intens, boîte EDC fluide, GPS R-Link, caméra de recul. Véhicule confortable et bien équipé pour la route.",
    highlights: ["Boîte EDC", "GPS R-Link", "Caméra de recul", "Sièges chauffants"],
    inspectionScore: 86,
    warrantyMonths: 6,
    available: true,
  },
  {
    id: "v010",
    slug: "citroen-berlingo-2021",
    brand: "Citroën",
    model: "Berlingo",
    version: "1.5 BlueHDi 130 XL Feel",
    year: 2021,
    price: 22500,
    monthlyPayment: 245,
    mileage: 61800,
    energy: "diesel",
    gearbox: "manuelle",
    body: "van",
    power: 130,
    critair: 2,
    location: "Showroom Juste à Rouler",
    type: "mandat",
    label: "garanti",
    image: "/images/vehicules/citroen-berlingo/face6.png",
    images: [
      "/images/vehicules/citroen-berlingo/face6.png",
      "/images/vehicules/citroen-berlingo/316b1c44-5542-4db8-b1a2-865160a6e502.png",
      "/images/vehicules/citroen-berlingo/4109f3cb-eb2a-4819-9a3d-761066e8380e.png",
      "/images/vehicules/citroen-berlingo/96d0ce9e-e641-4244-9103-3be926db96b3.png",
    ],
    description: "Citroën Berlingo XL 7 places, idéal famille nombreuse ou professionnel. Volume de chargement généreux, confort routier.",
    highlights: ["7 places", "Grand volume", "GPS", "Régulateur"],
    inspectionScore: 85,
    warrantyMonths: 6,
    available: true,
  },
  {
    id: "v011",
    slug: "mini-cooper-2022",
    brand: "Mini",
    model: "Cooper",
    version: "1.5 136 Chili BVA7",
    year: 2022,
    price: 25900,
    monthlyPayment: 279,
    mileage: 28400,
    energy: "essence",
    gearbox: "automatique",
    body: "citadine",
    power: 136,
    critair: 1,
    location: "Showroom Juste à Rouler",
    type: "stock",
    label: "garanti",
    image: "/images/vehicules/mini-cooper/face879.png",
    images: [
      "/images/vehicules/mini-cooper/face879.png",
      "/images/vehicules/mini-cooper/4073b9b8-b4b4-4917-958e-181ff236a399.png",
      "/images/vehicules/mini-cooper/47b1b06e-dd76-46be-a711-602bf92a1473.png",
      "/images/vehicules/mini-cooper/ChatGPT Image Feb 23, 2026, 09_59_13 PM.png",
    ],
    description: "Mini Cooper Chili, la citadine premium par excellence. Design iconique, conduite dynamique, équipement complet.",
    highlights: ["Pack Chili", "Toit Union Jack", "Écran tactile", "Conduite dynamique"],
    inspectionScore: 90,
    warrantyMonths: 12,
    available: true,
  },
  {
    id: "v012",
    slug: "indian-scout-bobber-2021",
    brand: "Indian",
    model: "Scout Bobber",
    version: "1133cc ABS",
    year: 2021,
    price: 13900,
    monthlyPayment: 159,
    mileage: 12400,
    energy: "essence",
    gearbox: "manuelle",
    body: "moto",
    power: 100,
    critair: 1,
    location: "Showroom Juste à Rouler",
    type: "stock",
    label: "sport",
    image: "/images/vehicules/indian-scout/face456.png",
    images: [
      "/images/vehicules/indian-scout/face456.png",
      "/images/vehicules/indian-scout/2965789b-2e16-4dec-a40a-1a2149220c9d.png",
      "/images/vehicules/indian-scout/b0e95478-7709-422a-9702-253fb8b422c0.png",
    ],
    description: "Indian Scout Bobber, style cruiser américain authentique. Faible kilométrage, entretien complet, passage banc validé.",
    highlights: ["Faible km", "Passage banc", "ABS", "État collection"],
    inspectionScore: 95,
    warrantyMonths: 6,
    available: true,
  },
  {
    id: "v013",
    slug: "iveco-daily-2020",
    brand: "Iveco",
    model: "Daily",
    version: "35C16 V16 Hi-Matic",
    year: 2020,
    price: 29900,
    monthlyPayment: 329,
    mileage: 87200,
    energy: "diesel",
    gearbox: "automatique",
    body: "utilitaire",
    power: 160,
    critair: 2,
    location: "Showroom Juste à Rouler",
    type: "mandat",
    label: "essentiel",
    image: "/images/vehicules/iveco-daily/face4894.png",
    images: [
      "/images/vehicules/iveco-daily/face4894.png",
      "/images/vehicules/iveco-daily/14134f37-b32d-4527-8fe8-23f51cd6b2e0.png",
      "/images/vehicules/iveco-daily/3586d255-730b-4742-ab3c-e946c3db3b15.png",
    ],
    description: "Iveco Daily Hi-Matic grand volume. Idéal pour les professionnels exigeants. Boîte automatique, charge utile importante.",
    highlights: ["Hi-Matic auto", "Grand volume", "Charge utile 1.5T", "GPS Pro"],
    inspectionScore: 82,
    warrantyMonths: 3,
    available: true,
  },
  {
    id: "v014",
    slug: "vw-transporter-2019",
    brand: "Volkswagen",
    model: "Transporter",
    version: "T6.1 2.0 TDI 150 Business Line DSG7",
    year: 2019,
    price: 34900,
    monthlyPayment: 379,
    mileage: 72100,
    energy: "diesel",
    gearbox: "automatique",
    body: "van",
    power: 150,
    critair: 2,
    location: "Showroom Juste à Rouler",
    type: "stock",
    label: "garanti",
    image: "/images/vehicules/vw-transporter/face654.png",
    images: [
      "/images/vehicules/vw-transporter/face654.png",
      "/images/vehicules/vw-transporter/7d2fd153-ea2f-408b-a428-02d7ce750790.png",
      "/images/vehicules/vw-transporter/fe41e032-d8eb-4787-8b97-b8853910fac7.png",
    ],
    description: "Volkswagen Transporter T6.1 Business Line. Base idéale pour aménagement van ou utilisation pro. Fiabilité allemande, boîte DSG.",
    highlights: ["DSG7", "Base van aménageable", "Climatisation", "Attelage"],
    inspectionScore: 88,
    warrantyMonths: 6,
    available: true,
  },
  {
    id: "v015",
    slug: "peugeot-boxer-2020",
    brand: "Peugeot",
    model: "Boxer",
    version: "2.2 BlueHDi 140 L3H2 Pro",
    year: 2020,
    price: 24500,
    monthlyPayment: 269,
    mileage: 95600,
    energy: "diesel",
    gearbox: "manuelle",
    body: "utilitaire",
    power: 140,
    critair: 2,
    location: "Showroom Juste à Rouler",
    type: "budget",
    label: "essentiel",
    image: "/images/vehicules/peugeot-boxer/face66.png",
    images: [
      "/images/vehicules/peugeot-boxer/face66.png",
      "/images/vehicules/peugeot-boxer/bcf8e742-2a24-4d23-93b1-52065cefc274.png",
      "/images/vehicules/peugeot-boxer/bd0d8a79-7996-4b81-9899-1fd05f968368.png",
      "/images/vehicules/peugeot-boxer/c422f92e-c41c-45aa-aefa-af4cfd7f3dc2.png",
    ],
    description: "Peugeot Boxer L3H2 Pro, grand volume utilitaire. Parfait pour les artisans et professionnels. Offre Essentiel au prix juste.",
    highlights: ["Grand volume L3H2", "GPS", "Charge utile 1.3T", "Prix serré"],
    inspectionScore: 78,
    warrantyMonths: 3,
    available: true,
  },
  {
    id: "v016",
    slug: "renault-express-2022",
    brand: "Renault",
    model: "Express Van",
    version: "1.5 dCi 95 Confort",
    year: 2022,
    price: 14900,
    monthlyPayment: 165,
    mileage: 43200,
    energy: "diesel",
    gearbox: "manuelle",
    body: "utilitaire",
    power: 95,
    critair: 2,
    location: "Showroom Juste à Rouler",
    type: "budget",
    label: "essentiel",
    image: "/images/vehicules/renault-express/face555.png",
    images: [
      "/images/vehicules/renault-express/face555.png",
      "/images/vehicules/renault-express/2202f66c-bb4b-465a-b094-5621521d78fc.png",
      "/images/vehicules/renault-express/82bb6aff-8b45-4e78-9f0c-c727f48fee0d.png",
      "/images/vehicules/renault-express/98bed716-2a42-4ef5-8ff3-47bfd5e7ec3c.png",
      "/images/vehicules/renault-express/cefe1942-00ae-44f3-8afb-2b5fe234ef81.png",
    ],
    description: "Renault Express Van Confort, utilitaire compact et économique. Parfait pour les livraisons urbaines et artisans. Prix imbattable.",
    highlights: ["Compact", "Économique", "Porte latérale", "Bluetooth"],
    inspectionScore: 81,
    warrantyMonths: 3,
    available: true,
  },
];

// Helper functions
export function getVehicleBySlug(slug: string): Vehicle | undefined {
  return vehicles.find((v) => v.slug === slug);
}

export function getUniqueBrands(): string[] {
  return [...new Set(vehicles.map((v) => v.brand))].sort();
}

export function getUniqueModels(): string[] {
  return [...new Set(vehicles.map((v) => v.model))].sort();
}

export function getPriceRange(): [number, number] {
  const prices = vehicles.map((v) => v.price);
  return [Math.min(...prices), Math.max(...prices)];
}

export const labelColors: Record<LabelLevel, { bg: string; text: string; label: string }> = {
  essentiel: { bg: "bg-gray-500/10", text: "text-gray-400", label: "Essentiel" },
  garanti: { bg: "bg-jar-orange/10", text: "text-jar-orange", label: "Garanti" },
  premium: { bg: "bg-amber-500/10", text: "text-amber-400", label: "Premium" },
  sport: { bg: "bg-red-500/10", text: "text-red-400", label: "Sport" },
};

export const typeLabels: Record<VehicleType, { label: string; color: string }> = {
  stock: { label: "En stock", color: "bg-green-500" },
  mandat: { label: "Dépôt-vente", color: "bg-blue-500" },
  budget: { label: "Essentiel", color: "bg-jar-gray" },
};
