export type VehicleType = "stock" | "mandat" | "budget";
export type LabelLevel = "essentiel" | "garanti" | "premium" | "sport";
export type EnergyType = "essence" | "diesel" | "hybride" | "electrique";
export type GearboxType = "manuelle" | "automatique";
export type BodyType = "berline" | "suv" | "utilitaire" | "van" | "moto" | "citadine" | "compacte" | "break";

export interface Vehicle {
  id: string;
  slug: string;
  brand: string;
  model: string;
  version: string;
  year: number;
  price: number;
  monthlyPayment: number;
  mileage: number;
  energy: EnergyType;
  gearbox: GearboxType;
  body: BodyType;
  power: number; // cv
  critair: number;
  location: string;
  type: VehicleType;
  label: LabelLevel;
  image: string;
  images: string[];
  description: string;
  highlights: string[];
  inspectionScore: number; // /100
  warrantyMonths: number;
  available: boolean;
}

export const vehicles: Vehicle[] = [
  {
    id: "v001",
    slug: "range-rover-sport-hse-2021",
    brand: "Land Rover",
    model: "Range Rover Sport",
    version: "3.0 SDV6 HSE Dynamic",
    year: 2021,
    price: 62900,
    monthlyPayment: 689,
    mileage: 47200,
    energy: "diesel",
    gearbox: "automatique",
    body: "suv",
    power: 306,
    critair: 2,
    location: "Showroom Juste à Rouler",
    type: "stock",
    label: "premium",
    image: "/images/vehicules/range-rover-sport/main.png",
    images: ["/images/vehicules/range-rover-sport/main.png"],
    description: "Range Rover Sport HSE Dynamic en excellent état. Véhicule Premium labellisé, historique complet, entretien à jour. Intérieur cuir, toit panoramique, système Meridian.",
    highlights: ["Toit panoramique", "Cuir intégral", "Caméra 360°", "Historique complet"],
    inspectionScore: 94,
    warrantyMonths: 12,
    available: true,
  },
  {
    id: "v002",
    slug: "audi-q5-sline-2022",
    brand: "Audi",
    model: "Q5",
    version: "40 TDI 204 S-Line Quattro S-Tronic",
    year: 2022,
    price: 44900,
    monthlyPayment: 489,
    mileage: 34500,
    energy: "diesel",
    gearbox: "automatique",
    body: "suv",
    power: 204,
    critair: 2,
    location: "Showroom Juste à Rouler",
    type: "stock",
    label: "garanti",
    image: "/images/vehicules/audi-q5/main.png",
    images: ["/images/vehicules/audi-q5/main.png"],
    description: "Audi Q5 S-Line Quattro, finition haut de gamme. Transmission intégrale, boîte S-Tronic 7 rapports. Véhicule labellisé Garanti 12 mois.",
    highlights: ["Quattro intégral", "Virtual cockpit", "Matrix LED", "Garantie 12 mois"],
    inspectionScore: 91,
    warrantyMonths: 12,
    available: true,
  },
  {
    id: "v003",
    slug: "peugeot-3008-gt-2023-bleu",
    brand: "Peugeot",
    model: "3008",
    version: "1.5 BlueHDi 130 GT EAT8",
    year: 2023,
    price: 32900,
    monthlyPayment: 359,
    mileage: 18700,
    energy: "diesel",
    gearbox: "automatique",
    body: "suv",
    power: 130,
    critair: 2,
    location: "Showroom Juste à Rouler",
    type: "stock",
    label: "garanti",
    image: "/images/vehicules/peugeot-3008-bleu/main.png",
    images: ["/images/vehicules/peugeot-3008-bleu/main.png"],
    description: "Peugeot 3008 GT de 2023, faible kilométrage. i-Cockpit, toit panoramique, aide à la conduite complète. Labellisé Garanti.",
    highlights: ["Faible kilométrage", "i-Cockpit 3D", "Toit panoramique", "Full LED"],
    inspectionScore: 96,
    warrantyMonths: 12,
    available: true,
  },
  {
    id: "v004",
    slug: "peugeot-3008-allure-2020-rouge",
    brand: "Peugeot",
    model: "3008",
    version: "1.5 BlueHDi 130 Allure Business",
    year: 2020,
    price: 21900,
    monthlyPayment: 239,
    mileage: 78400,
    energy: "diesel",
    gearbox: "manuelle",
    body: "suv",
    power: 130,
    critair: 2,
    location: "Showroom Juste à Rouler",
    type: "mandat",
    label: "garanti",
    image: "/images/vehicules/peugeot-3008-rouge/main.png",
    images: ["/images/vehicules/peugeot-3008-rouge/main.png"],
    description: "Peugeot 3008 Allure Business très bien entretenu. Suivi concession complet. GPS, caméra de recul, régulateur adaptatif.",
    highlights: ["Suivi concession", "GPS intégré", "Caméra de recul", "Apple CarPlay"],
    inspectionScore: 87,
    warrantyMonths: 6,
    available: true,
  },
  {
    id: "v005",
    slug: "audi-a3-sportback-2022",
    brand: "Audi",
    model: "A3 Sportback",
    version: "35 TFSI 150 S-Tronic Design Luxe",
    year: 2022,
    price: 31500,
    monthlyPayment: 345,
    mileage: 29800,
    energy: "essence",
    gearbox: "automatique",
    body: "compacte",
    power: 150,
    critair: 1,
    location: "Showroom Juste à Rouler",
    type: "stock",
    label: "garanti",
    image: "/images/vehicules/audi-a3/main.png",
    images: ["/images/vehicules/audi-a3/main.png"],
    description: "Audi A3 Sportback Design Luxe, finition haut de gamme. Cockpit digital, sièges chauffants, éclairage d'ambiance. État remarquable.",
    highlights: ["Cockpit digital", "Sièges chauffants", "Bang & Olufsen", "Carnet complet"],
    inspectionScore: 93,
    warrantyMonths: 12,
    available: true,
  },
  {
    id: "v006",
    slug: "audi-a1-sportback-2021",
    brand: "Audi",
    model: "A1 Sportback",
    version: "30 TFSI 116 S-Line",
    year: 2021,
    price: 22900,
    monthlyPayment: 249,
    mileage: 41200,
    energy: "essence",
    gearbox: "manuelle",
    body: "citadine",
    power: 116,
    critair: 1,
    location: "Showroom Juste à Rouler",
    type: "mandat",
    label: "garanti",
    image: "/images/vehicules/audi-a1/main.png",
    images: ["/images/vehicules/audi-a1/main.png"],
    description: "Audi A1 S-Line compacte et dynamique. Idéale en ville, finition soignée. GPS, régulateur, jantes 17 pouces.",
    highlights: ["Pack S-Line", "GPS MMI", "Jantes 17\"", "Radar de recul"],
    inspectionScore: 89,
    warrantyMonths: 6,
    available: true,
  },
  {
    id: "v007",
    slug: "audi-q3-sportback-2023",
    brand: "Audi",
    model: "Q3 Sportback",
    version: "35 TDI 150 S-Tronic S-Line",
    year: 2023,
    price: 41500,
    monthlyPayment: 449,
    mileage: 15600,
    energy: "diesel",
    gearbox: "automatique",
    body: "suv",
    power: 150,
    critair: 2,
    location: "Showroom Juste à Rouler",
    type: "stock",
    label: "premium",
    image: "/images/vehicules/audi-q3/main.png",
    images: ["/images/vehicules/audi-q3/main.png"],
    description: "Audi Q3 Sportback S-Line quasi neuf. Silhouette coupée, intérieur premium, technologies de pointe. Labellisé Premium.",
    highlights: ["Quasi neuf", "Virtual cockpit+", "Matrix LED", "Caméra 360°"],
    inspectionScore: 97,
    warrantyMonths: 12,
    available: true,
  },
  {
    id: "v008",
    slug: "citroen-c3-feel-2022",
    brand: "Citroën",
    model: "C3",
    version: "1.2 PureTech 83 Feel Pack",
    year: 2022,
    price: 13900,
    monthlyPayment: 149,
    mileage: 32100,
    energy: "essence",
    gearbox: "manuelle",
    body: "citadine",
    power: 83,
    critair: 1,
    location: "Showroom Juste à Rouler",
    type: "budget",
    label: "essentiel",
    image: "/images/vehicules/citroen-c3/main.png",
    images: ["/images/vehicules/citroen-c3/main.png"],
    description: "Citroën C3 Feel Pack, parfaite citadine. Confortable, économique, fiable. Idéale pour un premier véhicule ou un usage quotidien malin.",
    highlights: ["Économique", "Apple CarPlay", "Radar de recul", "Faible consommation"],
    inspectionScore: 84,
    warrantyMonths: 3,
    available: true,
  },
  {
    id: "v009",
    slug: "renault-megane-intens-2021",
    brand: "Renault",
    model: "Mégane",
    version: "1.3 TCe 140 Intens EDC",
    year: 2021,
    price: 18500,
    monthlyPayment: 199,
    mileage: 54300,
    energy: "essence",
    gearbox: "automatique",
    body: "compacte",
    power: 140,
    critair: 1,
    location: "Showroom Juste à Rouler",
    type: "mandat",
    label: "garanti",
    image: "/images/vehicules/renault-megane/main.png",
    images: ["/images/vehicules/renault-megane/main.png"],
    description: "Renault Mégane Intens, boîte EDC fluide, GPS R-Link, caméra de recul. Véhicule confortable et bien équipé pour la route.",
    highlights: ["Boîte EDC", "GPS R-Link", "Caméra de recul", "Sièges chauffants"],
    inspectionScore: 86,
    warrantyMonths: 6,
    available: true,
  },
  {
    id: "v010",
    slug: "citroen-berlingo-2021",
    brand: "Citroën",
    model: "Berlingo",
    version: "1.5 BlueHDi 130 XL Feel",
    year: 2021,
    price: 22500,
    monthlyPayment: 245,
    mileage: 61800,
    energy: "diesel",
    gearbox: "manuelle",
    body: "van",
    power: 130,
    critair: 2,
    location: "Showroom Juste à Rouler",
    type: "mandat",
    label: "garanti",
    image: "/images/vehicules/citroen-berlingo/main.png",
    images: ["/images/vehicules/citroen-berlingo/main.png"],
    description: "Citroën Berlingo XL 7 places, idéal famille nombreuse ou professionnel. Volume de chargement généreux, confort routier.",
    highlights: ["7 places", "Grand volume", "GPS", "Régulateur"],
    inspectionScore: 85,
    warrantyMonths: 6,
    available: true,
  },
  {
    id: "v011",
    slug: "mini-cooper-2022",
    brand: "Mini",
    model: "Cooper",
    version: "1.5 136 Chili BVA7",
    year: 2022,
    price: 25900,
    monthlyPayment: 279,
    mileage: 28400,
    energy: "essence",
    gearbox: "automatique",
    body: "citadine",
    power: 136,
    critair: 1,
    location: "Showroom Juste à Rouler",
    type: "stock",
    label: "garanti",
    image: "/images/vehicules/mini-cooper/main.png",
    images: ["/images/vehicules/mini-cooper/main.png"],
    description: "Mini Cooper Chili, la citadine premium par excellence. Design iconique, conduite dynamique, équipement complet.",
    highlights: ["Pack Chili", "Toit Union Jack", "Écran tactile", "Conduite dynamique"],
    inspectionScore: 90,
    warrantyMonths: 12,
    available: true,
  },
  {
    id: "v012",
    slug: "indian-scout-bobber-2021",
    brand: "Indian",
    model: "Scout Bobber",
    version: "1133cc ABS",
    year: 2021,
    price: 13900,
    monthlyPayment: 159,
    mileage: 12400,
    energy: "essence",
    gearbox: "manuelle",
    body: "moto",
    power: 100,
    critair: 1,
    location: "Showroom Juste à Rouler",
    type: "stock",
    label: "sport",
    image: "/images/vehicules/indian-scout/main.png",
    images: ["/images/vehicules/indian-scout/main.png"],
    description: "Indian Scout Bobber, style cruiser américain authentique. Faible kilométrage, entretien complet, passage banc validé.",
    highlights: ["Faible km", "Passage banc", "ABS", "État collection"],
    inspectionScore: 95,
    warrantyMonths: 6,
    available: true,
  },
  {
    id: "v013",
    slug: "iveco-daily-2020",
    brand: "Iveco",
    model: "Daily",
    version: "35C16 V16 Hi-Matic",
    year: 2020,
    price: 29900,
    monthlyPayment: 329,
    mileage: 87200,
    energy: "diesel",
    gearbox: "automatique",
    body: "utilitaire",
    power: 160,
    critair: 2,
    location: "Showroom Juste à Rouler",
    type: "mandat",
    label: "essentiel",
    image: "/images/vehicules/iveco-daily/main.png",
    images: ["/images/vehicules/iveco-daily/main.png"],
    description: "Iveco Daily Hi-Matic grand volume. Idéal pour les professionnels exigeants. Boîte automatique, charge utile importante.",
    highlights: ["Hi-Matic auto", "Grand volume", "Charge utile 1.5T", "GPS Pro"],
    inspectionScore: 82,
    warrantyMonths: 3,
    available: true,
  },
  {
    id: "v014",
    slug: "vw-transporter-2019",
    brand: "Volkswagen",
    model: "Transporter",
    version: "T6.1 2.0 TDI 150 Business Line DSG7",
    year: 2019,
    price: 34900,
    monthlyPayment: 379,
    mileage: 72100,
    energy: "diesel",
    gearbox: "automatique",
    body: "van",
    power: 150,
    critair: 2,
    location: "Showroom Juste à Rouler",
    type: "stock",
    label: "garanti",
    image: "/images/vehicules/vw-transporter/main.png",
    images: ["/images/vehicules/vw-transporter/main.png"],
    description: "Volkswagen Transporter T6.1 Business Line. Base idéale pour aménagement van ou utilisation pro. Fiabilité allemande, boîte DSG.",
    highlights: ["DSG7", "Base van aménageable", "Climatisation", "Attelage"],
    inspectionScore: 88,
    warrantyMonths: 6,
    available: true,
  },
  {
    id: "v015",
    slug: "peugeot-boxer-2020",
    brand: "Peugeot",
    model: "Boxer",
    version: "2.2 BlueHDi 140 L3H2 Pro",
    year: 2020,
    price: 24500,
    monthlyPayment: 269,
    mileage: 95600,
    energy: "diesel",
    gearbox: "manuelle",
    body: "utilitaire",
    power: 140,
    critair: 2,
    location: "Showroom Juste à Rouler",
    type: "budget",
    label: "essentiel",
    image: "/images/vehicules/peugeot-boxer/main.png",
    images: ["/images/vehicules/peugeot-boxer/main.png"],
    description: "Peugeot Boxer L3H2 Pro, grand volume utilitaire. Parfait pour les artisans et professionnels. Offre Essentiel au prix juste.",
    highlights: ["Grand volume L3H2", "GPS", "Charge utile 1.3T", "Prix serré"],
    inspectionScore: 78,
    warrantyMonths: 3,
    available: true,
  },
  {
    id: "v016",
    slug: "renault-express-2022",
    brand: "Renault",
    model: "Express Van",
    version: "1.5 dCi 95 Confort",
    year: 2022,
    price: 14900,
    monthlyPayment: 165,
    mileage: 43200,
    energy: "diesel",
    gearbox: "manuelle",
    body: "utilitaire",
    power: 95,
    critair: 2,
    location: "Showroom Juste à Rouler",
    type: "budget",
    label: "essentiel",
    image: "/images/vehicules/renault-express/main.png",
    images: ["/images/vehicules/renault-express/main.png"],
    description: "Renault Express Van Confort, utilitaire compact et économique. Parfait pour les livraisons urbaines et artisans. Prix imbattable.",
    highlights: ["Compact", "Économique", "Porte latérale", "Bluetooth"],
    inspectionScore: 81,
    warrantyMonths: 3,
    available: true,
  },
];

// Helper functions
export function getVehicleBySlug(slug: string): Vehicle | undefined {
  return vehicles.find((v) => v.slug === slug);
}

export function getUniqueBrands(): string[] {
  return [...new Set(vehicles.map((v) => v.brand))].sort();
}

export function getUniqueModels(): string[] {
  return [...new Set(vehicles.map((v) => v.model))].sort();
}

export function getPriceRange(): [number, number] {
  const prices = vehicles.map((v) => v.price);
  return [Math.min(...prices), Math.max(...prices)];
}

export const labelColors: Record<LabelLevel, { bg: string; text: string; label: string }> = {
  essentiel: { bg: "bg-gray-500/10", text: "text-gray-400", label: "Essentiel" },
  garanti: { bg: "bg-jar-orange/10", text: "text-jar-orange", label: "Garanti" },
  premium: { bg: "bg-amber-500/10", text: "text-amber-400", label: "Premium" },
  sport: { bg: "bg-red-500/10", text: "text-red-400", label: "Sport" },
};

export const typeLabels: Record<VehicleType, { label: string; color: string }> = {
  stock: { label: "En stock", color: "bg-green-500" },
  mandat: { label: "Dépôt-vente", color: "bg-blue-500" },
  budget: { label: "Essentiel", color: "bg-jar-gray" },
};
